services:
  - type: web
    name: pvscan
    env: python
    plan: free
    cache:
      - name: pip-cache
        path: /opt/render/project/.pip_cache
      - name: npm-cache
        path: pvscan-frontend-vite/node_modules
    buildCommand: |
      # --- Build frontend ---
      cd pvscan-frontend-vite
      npm install
      npm run build

      # --- Copy Vite build into backend ---
      rm -rf ../src/static/*
      cp -r dist/assets ../src/static/
      cp dist/index.html ../src/templates/index.html 

      # --- Install Python deps ---
      cd ..
      pip install -r requirements.txt

    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT src.main:app

    envVars:
      - key: SECRET_KEY
        generateValue: true
