services:
  - type: web
    name: pvscan
    env: python
    plan: free
    buildCommand: |
      # --- Build frontend ---
      cd pvscan-frontend-vite
      npm install
      npm run build

      # --- Copy Vue build into backend/static ---
      rm -rf ../pvscan_backend/src/static/*
      cp -r dist/* ../pvscan_backend/src/static/

      # --- Install Python deps ---
      cd ../pvscan_backend
      pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:$PORT pvscan_backend.src.main:app

    envVars:
      - key: SECRET_KEY
        generateValue: true
