services:
  - type: web
    name: pvscan-app
    env: python  
    buildCommand: |
      echo "--- Building Vue.js Frontend ---"
      cd pvscan-frontend && npm install && npm run build
      echo "--- Copying Frontend to Backend Static Folder ---"
      cp -r dist/* ../pvscan_backend/src/static/
      echo "--- Copying AI Models to Backend Static Folder ---"
      cp ../pvscan_backend/pvscan_mobilenetv3_v1.1.pth ../pvscan_backend/src/static/
      cp ../pvscan_backend/pvscan_mobilenetv3_v2.0.pth ../pvscan_backend/src/static/
      echo "--- Installing Python Backend Dependencies ---"
      cd ../pvscan_backend && pip install -r requirements.txt
      
    startCommand: cd pvscan_backend && gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: VUE_APP_API_BASE_URL
        value: https://pvscan-app.onrender.com
    plan: free
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - pvscan-frontend/**
        - pvscan_backend/**

